Feat/#24
Bamdoliro/o_o pull request #29
Opened 2023-12-02 14:54 UTC by seonghoon07

멤버페이지 필터기능 구현하였습니다

2023-12-02 15:25 UTC, SEOKKAMONI requested changes
음 코드를 봤는데 백엔드와 소통해서 쿼리문으로 frontend, backend를 날리면 그에 맞는 데이터를 주도록 바꾸면 더 좋을 것 같아요 해당 방법으로 소통 후 다시 리뷰 요청 부탁드려요~

2023-12-02 15:25 UTC, SEOKKAMONI commented on src/components/Header/index.js
>    const Items = ["팀 소개", "팀 문화", "프로젝트", "팀 연혁", "멤버 소개"];
Items는 너무 추상적인 네이밍이에요 좀 더 명시적인 네이밍으로 고치면 좋을 것 같네영!

2023-12-02 15:25 UTC, SEOKKAMONI commented on src/components/Project/index.js
> +          <S.Icon src={require(`../../assets/${symbol}`)} />
ES6 문법인 import로 고치면 좋을 것 같아욧

2023-12-03 15:23 UTC, SEOKKAMONI commented on src/components/Project/index.js
> +          <S.Icon src={require(`../../assets/${symbol}`)} />
앗 해당 symbol 확인을 못했네요 음~ 저라면

```suggestion
          <S.Icon src={`../../assets/${symbol}`} />
```

이렇게 할 것 같아요 require은 불필요해보여요!

2023-12-04 04:27 UTC, seonghoon07 commented on src/components/Header/index.js
>    const Items = ["팀 소개", "팀 문화", "프로젝트", "팀 연혁", "멤버 소개"];
routeItems로 변수명 변경하였습니닷

2023-12-04 14:52 UTC, SEOKKAMONI commented on src/pages/Layouts/Member/index.js
> +    console.log(`기수 : ${selectedGeneration.length}`)
```suggestion
```

불필요한 console.log는 지워줍시당

2023-12-04 14:52 UTC, SEOKKAMONI commented on src/pages/Layouts/Member/index.js
> +                selected={selectedPosition.includes(item)}
따로 추상화를 해주면 좋을것같아요

2023-12-04 14:52 UTC, SEOKKAMONI commented on src/pages/Layouts/Member/index.js
> +                    <S.GithubImg src={Github} />
```suggestion
                    <S.GithubImg src={githubImage} />
```
다음과 같이 네이밍을 좀 더 명시적으로 지어주면 좋을것같아여

2023-12-05 06:29 UTC, seonghoon07 commented on src/pages/Layouts/Member/index.js
> +    console.log(`기수 : ${selectedGeneration.length}`)
넵넵

2023-12-05 07:21 UTC, seonghoon07 commented on src/pages/Layouts/Member/index.js
> +                    <S.GithubImg src={Github} />
변경햇습니다!

2023-12-08 00:51 UTC, seonghoon07 commented on src/pages/Layouts/Member/index.js
> +  const handlePageChange = (page) => {
handleMemberPageChange로 변경하였습니다. 하지만 함수명이 너무 길어져 함수명 단축이 필요할 것 같습니다

2023-12-08 00:55 UTC, seonghoon07 commented on src/pages/Layouts/Member/index.js
> +        setFilteredMember(res.data)
Member 변수에는 api에서 불러온 모든 데이터들을 저장하고 filteredMember 변수에는 사용자가 필터기능으로 거른 멤버데이터들이 들어가게 됩니다. 저는 이 코드에서 setFilteredMember(res.data)를 삭제하고 필터기능을 구현한 useEffect의 dependency에 멤버를 추가함으로써 첫 리랜더링 때 Member들을 다 출력하였습니다

2023-12-08 01:18 UTC, seonghoon07 commented on src/pages/Layouts/Member/index.js
> +                selected={selectedPosition.includes(item)}
active 함수로 따로 빼두었습니다!

2023-12-08 01:18 UTC, seonghoon07 commented on src/pages/Layouts/Member/index.js
> +                selected={selectedGeneration.includes(item)}
active 함수로 따로 빼두었습니다!!!

2023-12-10 11:47 UTC, SEOKKAMONI approved these changes
Lgtm

2023-12-11 10:20 UTC, merged